### ISSUE TITLE
Make Application Login/Register Screen

### ISSUE THREAD

**Issue by NathanCarriere** [Jonathan204/StudyBuddy#2]
Note that the Register button should be changed, as per our cognitive walkthrough

**Comment by deleonkf** [comment]
![01_login](https://user-images.githubusercontent.com/44079021/111857037-cbf68900-88fc-11eb-8edc-9c302f0c8cc9.png)
![11_register_1](https://user-images.githubusercontent.com/44079021/111857039-cdc04c80-88fc-11eb-8a81-2917729cd570.png)
